# -*- coding: utf-8 -*-
"""producto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xHpyY9YavAfFIx9MRybyJgUASqnHSF-r
"""

def producto (a=int,b=int):
  multiplicacion= a * b
  return multiplicacion

print ( "El productos es: " , producto(2,4))